Update upload-to-azure.yml

diff --git a/.github/workflows/upload-to-azure.yml b/.github/workflows/upload-to-azure.yml
--- a/.github/workflows/upload-to-azure.yml
+++ b/.github/workflows/upload-to-azure.yml
@@ -16,19 +16,19 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Troubleshooting Secrets
-        run: |
-          echo "Checking Client ID..."
-          if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then echo "MISSING: AZURE_CLIENT_ID"; fi
-          echo "Checking Tenant ID..."
-          if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then echo "MISSING: AZURE_TENANT_ID"; fi
-          echo "Checking Subscription ID..."
-          if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then echo "MISSING: AZURE_SUBSCRIPTION_ID"; fi
+      # - name: Troubleshooting Secrets
+      #   run: |
+      #     echo "Checking Client ID..."
+      #     if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then echo "MISSING: AZURE_CLIENT_ID"; fi
+      #     echo "Checking Tenant ID..."
+      #     if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then echo "MISSING: AZURE_TENANT_ID"; fi
+      #     echo "Checking Subscription ID..."
+      #     if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then echo "MISSING: AZURE_SUBSCRIPTION_ID"; fi
 
-      - name: Hard Debug Secrets
-        run: |
-          echo "Total Repository Secrets: $(env | grep -c 'AZURE_')" # This should be > 0
-          [ -n "${{ secrets.AZURE_CLIENT_ID }}" ] && echo "Client ID Found" || echo "Client ID is MISSING"
+      # - name: Hard Debug Secrets
+      #   run: |
+      #     echo "Total Repository Secrets: $(env | grep -c 'AZURE_')" # This should be > 0
+      #     [ -n "${{ secrets.AZURE_CLIENT_ID }}" ] && echo "Client ID Found" || echo "Client ID is MISSING"
 
 
 
@@ -64,4 +64,5 @@ jobs:
               --container-name "github-uploads" \
               --file ./code.java \
               --name code.java
+              --overwrite true
 
